import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "./Providers";
import dynamic from "next/dynamic";

const CrispWithNoSSR = dynamic(() => import("../components/cirsp"), {
    ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "SocializeSpot - Blog App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-custom-color`}>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
